#!/bin/bash

D=$(dirname $0)

echo "building ..."
(cd $D && make)

echo "setting up for java 23 ..."
eval "$($D/cs java --jvm 23 --env)"

echo "running ..."
exec $D/target/universal/stage/bin/grader "$@"

