#!/bin/bash

D=$(dirname $0)

echo "building ..."
(cd $D && make)

JVM=$($D/jvm)
echo "setting up for $JVM ..."
eval "$($D/cs java --jvm "$JVM" --env)"
java -version

echo "running ..."
exec $D/target/universal/stage/bin/grader "$@"

