name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - name: Setup Coursier
      uses: coursier/setup-action@v1
      with:
        jvm: 23
        apps: sbt
    - name: Build and Test
      run: cs launch --jvm 23 sbt -- test
