name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: echo

    - name: Install dependencies
      run: echo

    - name: Run check
      run: make test

    - name: Run distcheck
      run: echo
